name: mobile
description: 'A new Flutter project.'

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=3.2.4 <4.0.0'

dependencies:
    audioplayers: ^5.2.1
    camera: ^0.10.5+9
    chopper: ^6.1.1
    flutter:
        sdk: flutter
    flutter_local_notifications: ^17.0.0
    flutter_localizations:
        sdk: flutter
    get_it: ^7.6.7
    http: ^1.2.0
    image: ^4.1.7
    intl: any
    json_annotation: ^4.8.0
    logging: ^1.2.0
    provider: ^6.0.1
    socket_io_client: ^2.0.3+1

dev_dependencies:
    build_runner: ^2.3.3
    chopper_generator: ^6.0.0
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1
    json_serializable: ^6.6.1
    swagger_dart_code_generator: ^2.10.4

flutter:
    uses-material-design: true

    # Enable generation of localized Strings from arb files.
    generate: true

    assets:
        # Add assets from the images directory to the application.
        - assets/images/
        - assets/audio/